// <auto-generated />
namespace Village_MVC_WebApi_Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addCitizensTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCitizensTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201191019414_addCitizensTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
